DROP TABLE IF EXISTS OC;
DROP TABLE IF EXISTS PROPRIETAIRE;



CREATE TABLE IF NOT EXISTS PROPRIETAIRE(
	id INT
	, nom varchar(64)
	, PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS OC (
  id INT AUTO_INCREMENT
	, nom varchar(64)
  , description varchar(2000)
  , prop INT
  , CONSTRAINT fk_oc_prop FOREIGN KEY (prop) REFERENCES PROPRIETAIRE(id)
	, PRIMARY KEY (id,prop)
);

INSERT INTO PROPRIETAIRE VALUES (3,"test")
INSERT INTO OC VALUES (NULL,"persotest","une description",3)
